# n_bootstraps: Number of bootstrapped samples to run
# query_ligand_column: Name of the column containing the query ligand id
# reference_ligand_column: Name of the column containing the reference ligand id
# reference_structure_column: Name of the column to distinguish reference structures by
# pose_id_column: Name of the column containing the pose id
# n_poses: Number of poses to select
# use_random_split: 
# n_per_split: A list of the number of reference structures that will be used in each split
# use_date_split: 
# reference_structure_date_column: Name of the column where the date of the reference structure deposition is saved
# randomize_by_n_days: 
# use_similarity_split: 
# similarity_column_name: Name of the column containing the similarity value between the query and reference ligands
# similarity_groupby: 
# similarity_range: Range of values the similarity score can take. Used to generate a standardized set of thresholds
# similarity_n_thresholds: Number of thresholds to use
# use_scaffold_split: 
# scaffold_split_option: How to split the data by scaffold, one of <enum 'ScaffoldSplitOptions'>
# query_scaffold_id_column: Name of the column containing the query scaffold id
# reference_scaffold_id_column: Name of the column containing the reference scaffold id
# query_scaffold_id_subset: List of query scaffold IDs to consider
# reference_scaffold_id_subset: List of reference scaffold IDs to consider
# query_scaffold_min_count: Minimum number of ligands in a query scaffold to consider it for docking
# reference_scaffold_min_count: Minimum number of ligands in a reference scaffold to consider it for docking
# combine_core_and_chemical_splits: Combine harbor.analysis.cross_docking.RandomSplit | harbor.analysis.cross_docking.DateSplit and harbor.analysis.cross_docking.SimilaritySplit | harbor.analysis.cross_docking.ScaffoldSplit into single splits
# use_posit_scorer: 
# posit_score_column_name: Name of the column containing the POSIT score
# posit_name: Name of the POSIT score
# use_rmsd_scorer: 
# rmsd_column_name: 
# rmsd_name: Name of the RMSD score
# rmsd_cutoff: RMSD cutoff to label the resulting poses as successful
n_bootstraps: 1000
query_ligand_column: Query_Ligand
reference_ligand_column: Reference_Ligand
reference_structure_column: Reference_Structure
pose_id_column: Pose_ID
n_poses:
- 1
use_random_split: true
update_n_per_split: true
use_date_split: true
reference_structure_date_column: Reference_Structure_Date
randomize_by_n_days: 1
use_similarity_split: false
similarity_column_name: null
similarity_groupby: {}
similarity_range:
- 0
- 1
similarity_n_thresholds: 21
use_scaffold_split: true
scaffold_split_option: x_to_all
query_scaffold_id_column: cluster_id
reference_scaffold_id_column: cluster_id_Reference
query_scaffold_id_subset: null
reference_scaffold_id_subset: null
query_scaffold_min_count: 5
reference_scaffold_min_count: 1
combine_core_and_chemical_splits: true
use_posit_scorer: true
posit_score_column_name: docking-confidence-POSIT
posit_name: POSIT_Probability
use_rmsd_scorer: true
rmsd_column_name: RMSD
rmsd_name: RMSD
rmsd_cutoff: 2.0
