date_dict_path: /Users/alexpayne/Scientific_Projects/asapdiscovery-sars-retrospective/science/20240403_multi_pose_docking_v2/20240430_analyze_cross_docking_results/20240503_inputs_analysis/date_dict.json
n_bootstraps: 1
n_per_split:
- 1
- 5
- 10
- 100
- 205
n_poses:
- 1
- 10
- 50
n_structures:
- 1
- 10
pose_id_column: Pose_ID
query_ligand_column: Query_Ligand
reference_ligand_column: Reference_Ligand
reference_structure_column: Reference_Structure
rmsd_cutoff: 2.0
