#!/usr/bin/env nextflow
include {
    PREP_CACHE_FOR_DOCKING
    GENERATE_COMBINED_LIGAND_FILES
    GENERATE_SPLIT_LIGAND_FILES
} from "./modules.nf"

workflow {
    PREP_CACHE_FOR_DOCKING()
    GENERATE_LIGAND_FILES((PREP_CACHE_FOR_DOCKING.out.fragalysisCache))
    GENERATE_SPLIT_LIGAND_FILES(GENERATE_COMBINED_LIGAND_FILES.out.ligandFile3d, GENERATE_COMBINED_LIGAND_FILES.out.ligandFile2d)
}
