"""
This script generates a combined 2D SDF file from a cache of moonshot data.
"""

from pathlib import Path
from asapdiscovery.modeling.protein_prep import ProteinPrepper
from asapdiscovery.data.schema.ligand import Ligand, write_ligands_to_multi_sdf
import argparse
from asapdiscovery.data.util.logging import FileLogger


def args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input_cache', type=Path, help='Path to input cache generated by the asapdiscovery-data package')
    parser.add_argument('-o', '--output_dir', type=Path, help='Path to output path')
    return parser.parse_args()


def combine_sdfs(data_dir, output_dir):
    complexes = ProteinPrepper.load_cache(data_dir)
    logger = FileLogger("combine_sdfs", output_dir, logfile="combine_sdfs.log").getLogger()
    logger.info(f"Found {len(complexes)} complexes in the cache: '{data_dir}'")
    ligands = [Ligand.from_smiles(complex.ligand.smiles,
                                  tags=complex.ligand.tags,
                                  compound_name=complex.ligand.compound_name,
                                  ids=complex.ligand.ids)
               for complex in complexes]
    write_ligands_to_multi_sdf(output_dir / 'combined.sdf', ligands)
    logger.info(f"Combined {len(ligands)} ligands into {output_dir / 'combined.sdf'}")


if __name__ == '__main__':
    args = args()
    combine_sdfs(args.input_cache, args.output_dir)